name: Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Run vcvarsall.bat
      run: & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
    - uses: actions/setup-python@v1
    - uses: mihails-strasuns/setup-dlang@v0.5.0
      with:
        compiler: dmd-2.091.0
    - name: Install Meson
      run: pip install meson
    - uses: actions/checkout@v1
    - name: Configure build
      run: meson build
    - name: Compile
      run: ninja -C build
    - uses: actions/upload-artifact@v2-preview
      with:
        name: CheeseCutter
        path: build/*.[ed]*