name: Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install LLVM
      run: choco install llvm
    - uses: ilammy/msvc-dev-cmd@v1.0.1
    - uses: actions/setup-python@v1
    - uses: mihails-strasuns/setup-dlang@v0.5.0
      with:
        compiler: dmd-2.091.0
    - name: Install Meson
      run: pip install meson
    - uses: actions/checkout@v1
    - name: Configure build
      run: meson setup build --backend ninja
    - uses: actions/upload-artifact@v2-preview
      if: failure()
      with:
        name: meson-log.txt
        path: build/meson-logs/meson-log.txt
    - name: Compile
      run: ninja -C build
    - uses: actions/upload-artifact@v2-preview
      with:
        name: CheeseCutter
        path: build/*.[ed]*
